name: Build Android APK (Capacitor)

on:
  push:
    branches: [ main ]
    paths:
      - "src/**/*"
      - "public/**/*"
      - "package.json"
      - "vite.config.js"
      - "capacitor.config.json"
      - ".github/workflows/build-android.yml"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            api/package-lock.json

      # 修复核心步骤：解决 Pinia 版本冲突
      - name: Install root dependencies (fix Pinia conflict)
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          # 降级 pinia-plugin-persistedstate 到兼容 Pinia 2.x 的版本
          npm install pinia-plugin-persistedstate@3.2.1  # 3.x 版本兼容 Pinia 2.x
          # 安装其他依赖（包含 Pinia 2.x）
          npm install
          # 验证 Capacitor CLI
          npx cap --version || exit 1

      - name: Install API dependencies
        run: |
          cd api
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
          cd ..

      - name: Build frontend with Vite
        run: |
          npm run build
          [ -d "dist" ] || { echo "Vite build failed"; exit 1; }

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          android-version: 34
          build-tools-version: 34.0.0

      - name: Set up Capacitor Android
        run: |
          npx cap add android
          npx cap sync android
          [ -d "android" ] || { echo "Capacitor Android setup failed"; exit 1; }

      - name: Build Android Debug APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace
          [ -f "app/build/outputs/apk/debug/app-debug.apk" ] || { echo "APK build failed"; exit 1; }

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: MoeKoe-Music-Android-Debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
