name: Build Android APK (Capacitor)

on:
  push:
    branches: [ main ]
    paths:
      - "src/**/*"
      - "public/**/*"
      - "package.json"
      - "vite.config.js"
      - "capacitor.config.json"
      - ".github/workflows/build-android.yml"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 20 (with latest npm)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            api/package-lock.json
      - name: Upgrade npm to latest version
        run: npm install -g npm@latest  # 确保 npm 版本 ≥7.1，支持 set-script

      # 修复：用升级后的 npm 配置 Capacitor 脚本
      - name: Install dependencies & configure Capacitor
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          # 1. 安装冲突依赖（Pinia 兼容版）
          npm install pinia@^2.2.4 pinia-plugin-persistedstate@3.2.1
          # 2. 安装 Capacitor v6+
          npm install @capacitor/cli@^6.1.0 @capacitor/core@^6.1.0 @capacitor/android@^6.1.0
          # 3. 安装其他依赖
          npm install
          # 4. 用升级后的 npm 添加 Capacitor 调用脚本
          npm set-script cap "node node_modules/@capacitor/cli/dist/cap.js"
          # 5. 验证脚本是否生效
          if ! npm run cap -- --version; then
            echo "Error: Capacitor CLI initialization failed"
            exit 1
          fi

      - name: Install API dependencies
        run: |
          cd api
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
          cd ..

      - name: Build frontend with Vite
        run: |
          npm run build
          [ -d "dist" ] || { echo "Error: Vite build failed (dist missing)"; exit 1; }

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          android-version: 34
          build-tools-version: 34.0.0

      - name: Set up Capacitor Android
        run: |
          npm run cap -- add android
          npm run cap -- sync android
          [ -d "android" ] || { echo "Error: Capacitor Android project missing"; exit 1; }

      - name: Build Android Debug APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace
          [ -f "app/build/outputs/apk/debug/app-debug.apk" ] || { echo "Error: APK missing"; exit 1; }

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: MoeKoe-Music-Android-Debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
